services:
  dbservice:
    image: postgres:latest
    container_name: verapaydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: verapay

  redis:
    image: redis:latest
    container_name: verapayredis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redisroot
    #                                    ↑ password for security

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'