services:
  dbservice:
    image: postgres:latest
    container_name: verapaydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:latest
    container_name: verapayredis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}