services:
  dbservice:
    image: postgres:latest
    container_name: verapaydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: verapay
#    volumes:
#      - C:/Users/Nicko/Desktop/verapay/data:/var/lib/postgresql/data
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'