# debug settings
spring.jpa.show-sql=${SHOW_SQL:false}

management.endpoint.shutdown.access=none

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.tracing.sampling.probability=1.0

management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

